on:
  schedule:
    - cron: 0 3 * * 2,6
  pull_request:
    types: [opened, reopened, closed]
  repository_dispatch:
    types: [update-deps]

name: Update dependencies
jobs:
  update:
    name: Update npm dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set running flag
        run: echo "::set-env name=RUNNING::"
      - name: Set running flag
        run: echo "::set-env name=RUNNING::1"
        if: github.event_name == 'pull_request' && github.event.pull_request.head.user.id == github.event.pull_request.base.user.id && startsWith(github.head_ref, 'release/')
      - name: Set running flag
        run: |
          if [[ ! -f package.json ]] || [[ $(< package.json jq -r '.version == null') == 'true' ]]; then
            echo "::set-env name=RUNNING::"
          fi
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH_PREFIX: release/
        if: env.RUNNING

      - name: Update dependencies
        uses: technote-space/create-pr-action@gh-actions
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXECUTE_COMMANDS: |
            npx npm-check-updates -u --packageFile package.json
            yarn install
            yarn upgrade
            yarn audit
          COMMIT_MESSAGE: 'chore: update npm dependencies'
          PR_BRANCH_NAME: 'chore-npm-update-${PR_ID}'
          PR_TITLE: 'chore: update npm dependencies (${PR_MERGE_REF})'
          PR_DEFAULT_BRANCH_PREFIX: release/
          PR_DEFAULT_BRANCH_NAME: next-${CURRENT_VERSION}
          PR_DEFAULT_BRANCH_TITLE: 'feat: release'
          TARGET_BRANCH_PREFIX: release/
          AUTO_MERGE_THRESHOLD_DAYS: 14
